spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/cashier
---
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cashier?useUnicode=true&characterEncoding=utf8
    username: root
    password: flzx3qc
    driver-class-name: com.mysql.jdbc.Driver